# Generated by Django 5.1.15 on 2026-06-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_generator', '0002_alter_userotp_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
